[build]
  command = "npm run build"
  publish = ".next"

# Redirect for SPA routing (Next.js will handle client-side navigation)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify Forms headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[plugins]]
  package = "@netlify/plugin-nextjs"
