[build]
  command = "npm run build"
  publish = ".next"

# Redirect for SPA routing (Next.js will handle client-side navigation)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = ".next"

  # Optional: disable the strict “React-form check” if you
  # decide NOT to add the static detector file.
  # Uncomment the next two lines only in that case.
[build.environment]
NETLIFY_NEXT_VERIFY_FORMS = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[plugins]]
  package = "@netlify/plugin-nextjs"

