[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_EDGE_FUNCTIONS_BUILD = "true"

# Form handling
[forms]
  spam_protection = true

# Note: For Next.js apps, you typically don't need manual redirects
# since @netlify/plugin-nextjs handles routing automatically
# If you need specific redirects, uncomment and modify as needed:
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"

[[plugins]]
  package = "@netlify/plugin-nextjs"